# Generated by Django 4.2.14 on 2024-08-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_category_course_code_course_date_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
