# Generated by Django 4.2.14 on 2024-08-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_delete_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcetype",
            name="resource",
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
