# Generated by Django 3.2.25 on 2024-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_resourcetype_resource_resourcetype_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='course',
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='resources_files/'),
        ),
    ]
