# Generated by Django 4.2.14 on 2024-08-11 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_category_course_code_course_date_created_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="account_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="user_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatus",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="studentstatus",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
    ]
