# Generated by Django 3.2.25 on 2024-08-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
