# Generated by Django 3.2.25 on 2024-08-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
