# Generated by Django 4.2.14 on 2024-08-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherstatus",
            old_name="student",
            new_name="teacher",
        ),
    ]
