# Generated by Django 4.2.14 on 2024-08-11 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_rename_student_teacherstatus_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="account_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacherstatus",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacherstatus",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="teacherstatus",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.teacher",
            ),
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
