# Generated by Django 3.2.25 on 2024-09-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstatus',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
